apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: result
spec:
  promotionFlows:
    - name: development-staging
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - release
  concurrency: queue
