# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: notify-slack
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
    description: ""
spec:
  serviceAccountName: cf-default-promotion-workflows-sa
  entrypoint: main
  arguments:
    parameters:
      - name: APP_NAMESPACE
      - name: APP_NAME
      - name: REPO_URL
      - name: BRANCH
      - name: PATH
      - name: COMMIT_SHA
        value: ''
      - name: COMMIT_MESSAGE
        value: ''
      - name: COMMIT_AUTHOR
        value: ''
      - name: COMMIT_DATE
        value: ''
  templates:
    - name: main
      dag:
        tasks:
        - name: send-message
          templateRef:
            name: argo-hub.slack.0.0.2
            template: send-message
          arguments:
            parameters:
            - name: SLACK_HOOK_URL
              value: 'https://hooks.slack.com/services/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'
            - name: SLACK_TEXT
              value: ["{{workflow.parameters.APP_NAME}} has been promoted, thank you {{workflow.parameters.COMMIT_AUTHOR}}!"]
              