gitops-runtime:
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
  global:
    codefresh:
      accountId: 68a871ee79bc0d867e35dd09
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: production-1
      isConfigurationRuntime: true
