# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: ghcr.io/flavorplus/codefresh-sample-svc-c
  tag: 1.0.0
redis:
  usePassword: false
replicaCount: 1
