apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  project: cf-root-app-project
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,configurations/**/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,production-1/cf-gitops-runtime.yaml,production-1/default-git-source.yaml,production-1/demoapps.yaml,runtimes/production-1/**/*.yaml,runtimes/production-1/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/CentricCodefreshPOC/codefresh-configs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
