# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: aiforaplatform/codefresh-poc-svc-b
  tag: 1.0.0
redis:
  usePassword: false
replicaCount: 1
domain: cpi.centricsoftware.com
